# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2715c33086086035c5d21cd9ff83fef3359c83360efc9583355641bd5d8ae60ed71176e46536bdf5f8744027270d7fcc8416dea1b4ea0ff4215a712eb60399b4

test:
  secret_key_base: f436e8c29455b11359c7795b6a37a2ba8193e23a2b12f88047bd39a520e863ee997e59502f03c15f337f18da163369aa6fe88e4794dc71d2d7e7c7ad4bdd533f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
